# Generated by Django 4.2.13 on 2024-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='picture',
            field=models.ImageField(default='https://th.bing.com/th?q=Bowen+University+Span+Logo&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247', upload_to='RSA-Images'),
        ),
    ]
