# Generated by Django 4.2.13 on 2024-06-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hostel_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='picture',
        ),
    ]
