# Generated by Django 4.2.13 on 2024-06-13 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_hostel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
