# Generated by Django 4.2.13 on 2024-06-17 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('matric_no', models.CharField(max_length=11)),
                ('college', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('student_no', models.CharField(max_length=11)),
                ('parent_no', models.CharField(max_length=11)),
                ('resumption_date', models.DateField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
